fix event details to new vizzu version
vizzuhq/vizzu-story-js pull request #90
Opened 2023-12-12 14:04 UTC by dovicsin

2023-12-12 14:08 UTC, nandordevai submitted a review, later dismissed

2023-12-12 23:00 UTC, veghdev commented
@dovicsin please modify vizzu version:
- in vizzu-player.js line 72
- in package.json dependencies to ~0.9.0 and create new package-lock.json
- in tests/vizzu-player/jsdom/jest.config.js
- in tests/vizzu-player/jsdom/vp.attributes.test.js
and
- remove the vizzu-url attribute from src/example/index.html

2023-12-13 13:14 UTC, veghdev commented
please turn off d.ts check ```"type-src": "npx check-dts src/vizzu-story.d.ts || echo 'not checked'"```,
because it is difficult to fix, and the story is going to become a vizzu plugin in the near future, and until then we are not planning to change the api

2023-12-13 13:22 UTC, veghdev requested changes
event.data also used in:
docs/tutorial/building_blocks.md
docs/examples/proglangs/main.js

2023-12-14 10:06 UTC, veghdev approved these changes

2023-12-14 12:47 UTC, veghdev approved these changes

2023-12-14 12:48 UTC, merged